server:
  port: 10001
  servlet:
    context-path: /web-client


logging:
  level:
    root: info

ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间

spring:
  application:
    name: web-client
  main:
    allow-bean-definition-overriding: true

  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181

#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        namespace: 1d87abc1-08dc-49ee-a388-14cd380fad61
#        register-enabled: false #只开启服务发现不注册服务

eureka:
  client:
    # 是否将eureka自身作为应用注册到eureka注册中心,默认为true
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      # 这里可以填写所有的eureka服务器地址并以','分离，当前面不能注册时候,自动选择后面的进行注册，排除单点故障问题
      defaultZone: http://localhost:10000/eureka/

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true


